version: "3.7"

services:
  moodle_mariadb:
    build: "mariadb/"

    environment:
      MYSQL_ROOT_PASSWORD: "root"

    networks:
      - "moodle"

    ports:
      - "3306:3306"

    volumes:
      - "../.data/mariadb/:/var/lib/mysql/"

  moodle_nginx:
    build: "nginx/"

    depends_on:
      - "moodle_php"

    networks:
      - "moodle"

    ports:
      - "80:80"

    volumes:
      - "../vendor/moodle/moodle/:/var/www/html/"

  moodle_php:
    build: "php/"

    depends_on:
      - "moodle_mariadb"

    networks:
      - "moodle"

    volumes:
      - "../.data/moodle/:/var/www/moodledata/"
      - "../backup/:/var/www/html/mod/matrix/backup/"
      - "../composer.json/:/var/www/html/mod/matrix/composer.json"
      - "../db/:/var/www/html/mod/matrix/db/"
      - "../index.php/:/var/www/html/mod/matrix/index.php"
      - "../lang/:/var/www/html/mod/matrix/lang/"
      - "../lib.php/:/var/www/html/mod/matrix/lib.php"
      - "../mod_form.php/:/var/www/html/mod/matrix/mod_form.php"
      - "../pix/:/var/www/html/mod/matrix/pix/"
      - "../settings.php/:/var/www/html/mod/matrix/settings.php"
      - "../src/:/var/www/html/mod/matrix/src/"
      - "../vendor/:/var/www/html/mod/matrix/vendor/"
      - "../vendor/moodle/moodle/:/var/www/html/"
      - "../version.php/:/var/www/html/mod/matrix/version.php"
      - "../view.php/:/var/www/html/mod/matrix/view.php"

networks:
  moodle:
    driver: "bridge"
